---
abstract: 'split up a single input file into multiple files according to a column value'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  Image::Info: '0'
  Test::Deep: '0'
  Test::HTTP::LocalServer: '0.61'
  Test::More: '0'
  URI: '0'
  URI::file: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-part
no_index:
  directory:
    - t
    - inc
requires:
  Getopt::Long: '0'
  Pod::Usage: '0'
  perl: '5.006'
resources:
  repository: git://github.com/Corion/App-part.git
version: '0.07'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
